### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by roblee357** [YUNEEC/Android-Samples#2]
I'm getting this error when trying to sync.
Error:(34, 13) Failed to resolve: com.github.YUNEEC:Yuneec-SDK-Android:v0.5.4

I have this added to dependencies:
    compile 'com.github.YUNEEC:Yuneec-SDK-Android:v0.5.4'
 and this added in allprojects:
        maven {url 'https://jitpack.io'}

**Comment by julianoes** [comment]
Welcome @roblee357 and thanks for the note.
Please try again now, the problem should be resolved.

**Comment by roblee357** [comment]
It works now. Thanks!

**Comment by julianoes** [comment]
Cool, thanks for the feedback.
