### ISSUE TITLE
Not connecting to Camera

### ISSUE THREAD

**Issue by SundanceMediaGroup** [YUNEEC/Android-Samples#3]
Yuneec Updater is connected to access, I can manually download all firmware to the ST16S.
Using Updater, it shows it's connected to the aircraft/camera, because it knows the firmware version of AP and E90, and wants to update Gimbal. 
![image](https://user-images.githubusercontent.com/26231621/29998698-b7d4a0c8-8fe6-11e7-9313-4fe27b5ead5d.png)

The system will not update the Gimbal.
Additionally, the Updater is showing several E90 that have never been connected to the aircraft.
![image](https://user-images.githubusercontent.com/26231621/29998673-388c531a-8fe6-11e7-82ff-6f6ee00aff4d.png)

I have allowed it to cycle (continually tapping after the update indicator stops spinning) for 45 minutes with no change.

**Comment by SundanceMediaGroup** [comment]
Update:
After nearly an hour of cycling by itself, it finally downloaded the very small gimbal upgrade. It took approx 1 min to direct download, but nearly an hour over the ST16S connected to the same network.

![screenshot_2017-09-02-20-56-43](https://user-images.githubusercontent.com/26231621/29999119-292e3036-8ff1-11e7-96e3-a3ce324cd440.png)

**Comment by julianoes** [comment]
@SundanceMediaGroup this is the wrong repository for this issue, closing.
